Part A: Fitting multiple regression predicting sales using price, urban, and US.

Part B: Holding all variables constant each 1 dollar increase in price is expected to drop the predicted sales by 0.054 units. Being in an urban area vs. a non-urban area decreases sales by 0.022 units. Being in the US vs not being in the US increases sales by 1.201 units.

Part C: Predicted Sales = 13.043 + -0.054 * (Price) + -0.022 * (Urban) + 1.201 * (US)

Part D: Reject the null hypothesis for X1 (Price) and X3 (US). There is not sufficient evidence to reject the null hypothesis B = 0 for the predictor urban. 

Part E: Constructing model dropping X2 or Urban given non-significant 

Part F: The model from part A has an adjusted R-squared value of 0.234 and the model from part e has an adjusted R-squared value of 0.235. Therefore, for model A 23.4 percent of the variation in sales is explained by the variation in price, urban, and US.  While 23.5 percent of the variation in sales is explained by the variation in price, and US. Neither model is fits the data well, however, the simpler model appears to be slightly better. 

Part G: For Price the 95 percent confidence interval is [-0.065,-0.044] and for US it is [0.692,1.708]. Note 0 is not in the interval.

Part H: The p-values for omnibus and jarque-bera indicate that residuals do not significantly deviate from normality i.e. we fail to reject the null hypothesis that the residuals are normally distributed which suggests there is not strong evidence of outliers. Also the kurtosis value is 2.895 which is very close to 3 indicating no extreme tails. There are 20 high leverage values present. These are assigned by the equation 2(# predictors + 1) / (# observations). Therefore any leverage value greater than 0.015 is considered high leverage. 

Loading carseats data 

In [12]:
import pandas as pd

carseats = pd.read_csv("Carseats.csv")

print(carseats.head())


   Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No  


Part A: Fitting multiple regression predicting sales using price, urban, and US.

Part B: Holding all variables constant each 1 dollar increase in price is expected to drop the predicted sales by 0.054 units. Being in an urban area vs. a non-urban area decreases sales by 0.022 units. Being in the US vs not being in the US increases sales by 1.201 units.

Part C: Predicted Sales = 13.043 + -0.054 * (Price) + -0.022 * (Urban) + 1.201 * (US)

In [13]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


#reference level will be No
carseats['Urban'] = carseats['Urban'].map({'No': 0, 'Yes': 1})
carseats['US'] = carseats['US'].map({'No': 0, 'Yes': 1})

X = carseats[['Price', 'Urban', 'US']].values
y = carseats[['Sales']].values


MLRModel = LinearRegression()

MLRModel.fit(X, y)

print(
    "Predicted Sales = ",
    MLRModel.intercept_[0],
    " + ",
    MLRModel.coef_[0][0],
    "* (Price)",
    " + ",
    MLRModel.coef_[0][1],
    "* (Urban)",
    " + ",
    MLRModel.coef_[0][2],
    "* (US)",
)




Predicted Sales =  13.043468936764892  +  -0.054458849177582175 * (Price)  +  -0.021916150814141 * (Urban)  +  1.2005726977941158 * (US)


Model Metrics

Part D: Reject the null hypothesis for X1 (Price) and X3 (US). There is not sufficient evidence to reject the null hypothesis B = 0 for the predictor urban. 

In [14]:
import statsmodels.api as sm

#this is adding constant term for intercept
X = sm.add_constant(X)

# Fit the regression model
modelmetrics = sm.OLS(y, X).fit()

# Show Model Summary
print(modelmetrics.summary())




                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.239
Model:                            OLS   Adj. R-squared:                  0.234
Method:                 Least Squares   F-statistic:                     41.52
Date:                Mon, 03 Mar 2025   Prob (F-statistic):           2.39e-23
Time:                        17:27:35   Log-Likelihood:                -927.66
No. Observations:                 400   AIC:                             1863.
Df Residuals:                     396   BIC:                             1879.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         13.0435      0.651     20.036      0.0

Part E: Constructing model dropping X2 or Urban given non-significant 

In [ ]:


X = carseats[['Price', 'US']].values
y = carseats[['Sales']].values


MLRModel = LinearRegression()

MLRModel.fit(X, y)

print(
    "Predicted Sales = ",
    MLRModel.intercept_[0],
    " + ",
    MLRModel.coef_[0][0],
    "* (Price)",
    " + ",
    MLRModel.coef_[0][1],
    "* (US)",
)


Predicted Sales =  13.03079275461576  +  -0.054477632479787264 * (Price)  +  1.1996429432266784 * (US)


Simpler model metrics

In [ ]:
#this is adding constant term for intercept
X = sm.add_constant(X)

# Fit the regression model
modelmetrics = sm.OLS(y, X).fit()

# Show Model Summary
print(modelmetrics.summary())


# Compute influence measures
influence = modelmetrics.get_influence()

# leverage values 
leverage = influence.hat_matrix_diag

# 2(predictors+1) / (no. observations) gives 0.015 anything greater is considered high
high_leverage_count = sum(leverage > 0.015)
print("There are",high_leverage_count, "high leverage values.")

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.239
Model:                            OLS   Adj. R-squared:                  0.235
Method:                 Least Squares   F-statistic:                     62.43
Date:                Mon, 03 Mar 2025   Prob (F-statistic):           2.66e-24
Time:                        18:11:57   Log-Likelihood:                -927.66
No. Observations:                 400   AIC:                             1861.
Df Residuals:                     397   BIC:                             1873.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         13.0308      0.631     20.652      0.0

Part F: The model from part A has an adjusted R-squared value of 0.234 and the model from part e has an adjusted R-squared value of 0.235. Therefore, for model A 23.4 percent of the variation in sales is explained by price, urban, and US.  While 23.5 percent of the variation in sales is explained by price, and US. Neither model is fits the data well, however, the simpler model appears to be slightly better. 

Part G: For Price the 95 percent confidence interval is [-0.065,-0.044] and for US it is [0.692,1.708]. Note 0 is not in the interval.

Part H: The p-values for omnibus and jarque-bera indicate that residuals do not significantly deviate from normality i.e. we fail to reject the null hypothesis that the residuals are normally distributed which suggests there is not strong evidence of outliers. Also the kurtosis value is 2.895 which is very close to 3 indicating no extreme tails. There are 20 high leverage values present. These are assigned by the equation 2(# predictors + 1) / (# observations). Therefore any leverage value greater than 0.015 is considered high leverage. 